superhero_database/superhero_database/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_database/superheroes/urls.py
from . import views
from django.urls import path


app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:superhero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create_new_superhero')
]

superhero_database/superheroes/models.py
from django.db import models


class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_superhero_ability = models.CharField(max_length=50)
    secondary_superhero_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name
# Create your models here.

superhero_database/superheroes/views.py
from django.shortcuts import render
from .models import Superhero
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
# Create your views here.


def index(request):
    all_superheroes = Superhero.objects.all()
    context = {
        'all_superheroes': all_superheroes
    }
    return render(request, 'superheroes/index.html', context)


def detail(request, superhero_id):
    specific_superhero = Superhero.objects.get(id=superhero_id)
    context = {
        'specific_superhero': specific_superhero
    }
    return render(request, 'superheroes/detail.html', context)


def create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_superhero_ability = request.POST.get('primary_superhero_ability')
        secondary_superhero_ability = request.POST.get('secondary_superhero_ability')
        catch_phrase = request.POST.get('catch_phrase')
        new_superhero = Superhero(name=name, alter_ego=alter_ego, primary_superhero_ability=primary_superhero_ability, secondary_superhero_ability=secondary_superhero_ability, catch_phrase=catch_phrase)
        new_superhero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

superhero_database/superheroes/templates/superheroes/create.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Create Superhero</title>
</head>
<body>
<form action="{% url 'superheroes:create_new_superhero' %}" method="post">
  {% csrf_token %}
  Name:<input type="text" name="name" id="name"><br>
  Alter ego:<input type="text" name="alter_ego" id="alter_ego"><br>
  Primary superhero ability:<input type="text" name="primary_superhero_ability" id="primary_superhero_ability"><br>
  Secondary superhero ability:<input type="text" name="secondary_superhero_ability" id="secondary_superhero_ability"><br>
  Catch phrase:<input type="text" name="catch_phrase" id="catch_phrase"><br>
    <input type="submit" value="Add new!">
</form>
</body>
</html>

superhero_database/superheroes/templates/superheroes/detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Superhero detail</title>
</head>
<body>
<ul>

    <li><h2>{{specific_superhero.name}}</h2></li>
    <li><h2>{{specific_superhero.alter_ego}}</h2></li>
    <li><h2>{{specific_superhero.primary_superhero_ability}}</h2></li>
    <li><h2>{{specific_superhero.secondary_superhero_ability}}</h2></li>
    <li><h2>{{specific_superhero.catch_phrase}}</h2></li>

</ul>
</body>
</html>

superhero_database/superheroes/templates/superheroes/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Superhero Index</title>
</head>
<body>
<h1>This is a templated view!</h1>
<ul>
    {% for superhero in all_superheroes %}
    <li><h2>{{superhero.name}}</h2></li>
    {% endfor %}
</ul>
</body>
</html>